groups:
- name: node-exporter
  rules:
  - alert: NodeOutOfMemory
    annotations:
      summary: Node out of memory (instance {{ $labels.instance }})
      description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    labels:
      severity: warning
    expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
    for: 2m

  - alert: NodeMemoryUnderMemoryPressure
    annotations:
      summary: Node memory under memory pressure (instance {{ $labels.instance }})
      description: "The node is under heavy memory pressure. High rate of major page faults\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    labels:
      severity: warning
    expr: (rate(node_vmstat_pgmajfault[1m]) > 1000) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
    for: 2m

  - alert: NodeFilesystemSpaceFillingUp
    annotations:
      description: "Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available space left and is filling up."
      summary: "Filesystem is predicted to run out of space within the next 24 hours."
    expr: |
      (
        node_filesystem_avail_bytes{job="node",fstype!=""} / node_filesystem_size_bytes{job="node",fstype!=""} * 100 < 40
      and
        predict_linear(node_filesystem_avail_bytes{job="node",fstype!=""}[6h], 24*60*60) < 0
      and
        node_filesystem_readonly{job="node",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: warning
  - alert: NodeFilesystemSpaceFillingUp
    annotations:
      description: "Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available space left and is filling up fast."
      summary: "Filesystem is predicted to run out of space within the next 4 hours."
    expr: |
      (
        node_filesystem_avail_bytes{job="node",fstype!=""} / node_filesystem_size_bytes{job="node",fstype!=""} * 100 < 20
      and
        predict_linear(node_filesystem_avail_bytes{job="node",fstype!=""}[6h], 4*60*60) < 0
      and
        node_filesystem_readonly{job="node",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: critical
  - alert: NodeFilesystemAlmostOutOfSpace
    annotations:
      description: "Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available space left."
      summary: "Filesystem has less than 5% space left."
    expr: |
      (
        node_filesystem_avail_bytes{job="node",fstype!=""} / node_filesystem_size_bytes{job="node",fstype!=""} * 100 < 5
      and
        node_filesystem_readonly{job="node",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: warning
  - alert: NodeFilesystemAlmostOutOfSpace
    annotations:
      description: "Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available space left."
      summary: "Filesystem has less than 3% space left."
    expr: |
      (
        node_filesystem_avail_bytes{job="node",fstype!=""} / node_filesystem_size_bytes{job="node",fstype!=""} * 100 < 3
      and
        node_filesystem_readonly{job="node",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: critical
  - alert: NodeFilesystemFilesFillingUp
    annotations:
      description: "Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available inodes left and is filling up."
      summary: "Filesystem is predicted to run out of inodes within the next 24 hours."
    expr: |
      (
        node_filesystem_files_free{job="node",fstype!=""} / node_filesystem_files{job="node",fstype!=""} * 100 < 40
      and
        predict_linear(node_filesystem_files_free{job="node",fstype!=""}[6h], 24*60*60) < 0
      and
        node_filesystem_readonly{job="node",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: warning
  - alert: NodeFilesystemFilesFillingUp
    annotations:
      description: "Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available inodes left and is filling up fast."
      summary: "Filesystem is predicted to run out of inodes within the next 4 hours."
    expr: |
      (
        node_filesystem_files_free{job="node",fstype!=""} / node_filesystem_files{job="node",fstype!=""} * 100 < 20
      and
        predict_linear(node_filesystem_files_free{job="node",fstype!=""}[6h], 4*60*60) < 0
      and
        node_filesystem_readonly{job="node",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: critical
  - alert: NodeFilesystemAlmostOutOfFiles
    annotations:
      description: "Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available inodes left."
      summary: "Filesystem has less than 5% inodes left."
    expr: |
      (
        node_filesystem_files_free{job="node",fstype!=""} / node_filesystem_files{job="node",fstype!=""} * 100 < 5
      and
        node_filesystem_readonly{job="node",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: warning
  - alert: NodeFilesystemAlmostOutOfFiles
    annotations:
      description: "Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available inodes left."
      summary: "Filesystem has less than 3% inodes left."
    expr: |
      (
        node_filesystem_files_free{job="node",fstype!=""} / node_filesystem_files{job="node",fstype!=""} * 100 < 3
      and
        node_filesystem_readonly{job="node",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: critical
  - alert: NodeNetworkReceiveErrs
    annotations:
      description: "{{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf \"%.0f\" $value }} receive errors in the last two minutes."
      summary: "Network interface is reporting many receive errors."
    expr: |
      rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m]) > 0.01
    for: 1h
    labels:
      severity: warning
  - alert: NodeNetworkTransmitErrs
    annotations:
      description: "{{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf \"%.0f\" $value }} transmit errors in the last two minutes."
      summary: "Network interface is reporting many transmit errors."
    expr: |
      rate(node_network_transmit_errs_total[2m]) / rate(node_network_transmit_packets_total[2m]) > 0.01
    for: 1h
    labels:
      severity: warning
  - alert: "NodeHighNumberConntrackEntriesUsed"
    annotations:
      description: "{{ $value | humanizePercentage }} of conntrack entries are used."
      summary: "Number of conntrack are getting close to the limit."
    expr: |
      (node_nf_conntrack_entries / node_nf_conntrack_entries_limit) > 0.75
    labels:
      severity: warning
  - alert: NodeTextFileCollectorScrapeError
    annotations:
      description: "Node Exporter text file collector failed to scrape."
      summary: "Node Exporter text file collector failed to scrape."
    expr: |
      node_textfile_scrape_error{job="node"} == 1
    labels:
      severity: warning
  - alert: NodeClockSkewDetected
    annotations:
      description: "Clock on {{ $labels.instance }} is out of sync by more than 300s. Ensure NTP is configured correctly on this host."
      summary: "Clock skew detected."
    expr: |
      (
        node_timex_offset_seconds > 0.05
      and
        deriv(node_timex_offset_seconds[5m]) >= 0
      )
      or
      (
        node_timex_offset_seconds < -0.05
      and
        deriv(node_timex_offset_seconds[5m]) <= 0
      )
    for: 10m
    labels:
      severity: warning
  - alert: NodeClockNotSynchronising
    annotations:
      description: "Clock on {{ $labels.instance }} is not synchronising. Ensure NTP is configured on this host."
      summary: "Clock not synchronising."
    expr: |
      min_over_time(node_timex_sync_status[5m]) == 0
      and
      node_timex_maxerror_seconds >= 16
    for: 10m
    labels:
      severity: warning
  - alert: NodeRAIDDegraded
    annotations:
      description: "RAID array '{{ $labels.device }}' on {{ $labels.instance }} is in degraded state due to one or more disks failures. Number of spare drives is insufficient to fix issue automatically."
      summary: "RAID Array is degraded"
    expr: |
      node_md_disks_required - ignoring (state) (node_md_disks{state="active"}) > 0
    for: 15m
    labels:
      severity: critical
  - alert: NodeRAIDDiskFailure
    annotations:
      description: "At least one device in RAID array on {{ $labels.instance }} failed. Array '{{ $labels.device }}' needs attention and possibly a disk swap."
      summary: "Failed device in RAID array"
    expr: node_md_disks{state="failed"} > 0
    labels:
      severity: warning

- name: cadvisor
  rules:
  - alert: ContainerMemoryUsageHigh
    annotations:
      summary: "Container {{ $labels.name }} memory usage is high"
      description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 80% of its allocated memory.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: (container_memory_usage_bytes{container_label_com_docker_compose_config_hash=~".+", container_label_stackname="docker-monitoring-stack-gpnc"} / container_spec_memory_limit_bytes) > 0.8
    for: 5m
    labels:
      severity: warning

  - alert: ContainerMemoryAlmostOut
    annotations:
      summary: "Container {{ $labels.name }} memory almost full"
      description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 90% of its allocated memory.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: (container_memory_usage_bytes{container_label_com_docker_compose_config_hash=~".+", container_label_stackname="docker-monitoring-stack-gpnc"} / container_spec_memory_limit_bytes) > 0.9
    for: 2m
    labels:
      severity: critical

  - alert: ContainerCPUThrottlingHigh
    annotations:
      summary: "Container {{ $labels.name }} experiencing high CPU throttling"
      description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is experiencing high CPU throttling.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: rate(container_cpu_cfs_throttled_periods_total[5m]) / rate(container_cpu_cfs_periods_total[5m]) > 0.2
    for: 5m
    labels:
      severity: warning

  - alert: ContainerCPUUsageHigh
    annotations:
      summary: "Container {{ $labels.name }} CPU usage is high"
      description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 80% of its allocated CPU.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: rate(container_cpu_usage_seconds_total[1m]) > (container_spec_cpu_quota / container_spec_cpu_period * 0.8)
    for: 5m
    labels:
      severity: warning

  - alert: ContainerDiskUsageHigh
    annotations:
      summary: "Container {{ $labels.name }} disk usage is high"
      description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 80% of its disk quota.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: container_fs_usage_bytes / container_fs_limit_bytes > 0.8
    for: 5m
    labels:
      severity: warning

  - alert: ContainerDiskAlmostOut
    annotations:
      summary: "Container {{ $labels.name }} almost out of disk space"
      description: "The container {{ $labels.name }} on instance {{ $labels.instance }} is using more than 90% of its disk quota.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: container_fs_usage_bytes / container_fs_limit_bytes > 0.9
    for: 5m
    labels:
      severity: critical

  - alert: ContainerRestarts
    annotations:
      summary: "Container {{ $labels.name }} restarted"
      description: "The container {{ $labels.name }} on instance {{ $labels.instance }} has restarted more than 3 times in the last 5 minutes.\nVALUE = {{ $value }}\nLABELS = {{ $labels }}"
    expr: rate(container_restart_count_total[5m]) > 3
    for: 5m
    labels:
      severity: critical

